
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=sqlite:///secureflow.db
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    command: python start_server.py

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        - REACT_APP_API_URL=http://localhost:5001
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules

volumes:
  backend_data:
